height=[0,1,0,2,1,0,1,3,2,1,2,1]
n=len(height)
leftmax,rightmax,waterUnits=0,0,0
l=0
r=n-1
while(l<r):
    if(height[l]<=height[r]):
        if(leftmax>height[l]):
            waterUnits+=leftmax-height[l]
        else:
            leftmax=height[l]
        l+=1
    else:
        if(rightmax>height[r]):
            waterUnits+=rightmax-height[r]
        else:
            rightmax=height[r]
        r-=1
print(waterUnits," units")
